Summary  the Dataset:
This dataset contains monthly aggregated airline performance statistics grouped by airline carrier and airpor
Each row represents:
Carrier + Airport + Month + Year summary
So it shows totals like number of flights, number of delayed flights, and delay reasons.

Objectives:
Perform data cleaning and preprocessing.
Visualize correlations and delay distributions.
Understand main causes of airline delays.
Provide actionable recommendations based on data.

Purpose:
Help airlines improve scheduling, aircraft management, and operational efficiency.
Help airports improve infrastructure planning, staffing, and traffic management.
Help passengers choose better airlines, airports, and travel times.

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\santo\airline-delay\data\Airline_Delay_Cause.csv")

understanding the dataset:

In [3]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [13]:
df.shape

(171666, 21)

In [5]:


df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171666 entries, 0 to 171665
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 171666 non-null  int64
 1   month                171666 non-null  int64
 2   carrier              171666 non-null  object
 3   carrier_name         171666 non-null  object
 4   airport              171666 non-null  object
 5   airport_name         171666 non-null  object
 6   arr_flights          171426 non-null  float64
 7   arr_del15            171223 non-null  float64
 8   carrier_ct           171426 non-null  float64
 9   weather_ct           171426 non-null  float64
 10  nas_ct               171426 non-null  float64
 11  security_ct          171426 non-null  float64
 12  late_aircraft_ct     171426 non-null  float64
 13  arr_cancelled        171426 non-null  float64
 14  arr_diverted         171426 non-null  float64
 15  arr_delay            171426 non-null  float64
 16  carrier_delay        171426 non-null  float64
 17  weather_delay        171426 non-null  float64
 18  nas_delay            171426 non-null  float64
 19  security_delay       171426 non-null  float64
 20  late_aircraft_delay  171426 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 27.5+ MB

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,171666.000000,171666.000000,171426.000000,171223.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.00000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000
mean,2018.551361,6.493633,362.528467,66.434387,20.796615,2.250347,19.381147,0.157096,23.770554,7.530497,0.863387,4239.48733,1437.185124,222.563497,920.651704,7.382725,1651.700063
std,2.890006,3.440908,992.894662,179.540694,50.315176,7.314252,61.675244,0.717405,72.393477,43.654880,3.772853,12618.56605,4215.677812,821.086511,3423.509335,41.779985,5221.878385
min,2013.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2016.000000,4.000000,50.000000,6.000000,2.160000,0.000000,1.000000,0.000000,1.230000,0.000000,0.000000,335.00000,110.000000,0.000000,34.000000,0.000000,65.000000
50%,2019.000000,7.000000,100.000000,17.000000,6.400000,0.400000,3.910000,0.000000,5.000000,1.000000,0.000000,1018.00000,375.000000,18.000000,146.000000,0.000000,320.000000
75%,2021.000000,9.000000,250.000000,47.000000,17.260000,1.860000,11.710000,0.000000,15.260000,4.000000,1.000000,2884.00000,1109.000000,146.000000,477.000000,0.000000,1070.000000
max,2023.000000,12.000000,21977.000000,4176.000000,1293.910000,266.420000,1884.420000,58.690000,2069.070000,4951.000000,197.000000,438783.00000,196944.000000,31960.000000,112018.000000,3760.000000,227959.000000


#data cleaning

In [6]:
1)handle missing value :

In [7]:
 #Check Null Count in Each Column
print(df.isnull().sum())

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights            240
arr_del15              443
carrier_ct             240
weather_ct             240
nas_ct                 240
security_ct            240
late_aircraft_ct       240
arr_cancelled          240
arr_diverted           240
arr_delay              240
carrier_delay          240
weather_delay          240
nas_delay              240
security_delay         240
late_aircraft_delay    240
dtype: int64

In [8]:
print(df.isnull().sum()[df.isnull().sum() > 0])

arr_flights            240
arr_del15              443
carrier_ct             240
weather_ct             240
nas_ct                 240
security_ct            240
late_aircraft_ct       240
arr_cancelled          240
arr_diverted           240
arr_delay              240
carrier_delay          240
weather_delay          240
nas_delay              240
security_delay         240
late_aircraft_delay    240
dtype: int64

In [9]:
missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent[missing_percent > 0])

arr_flights            0.139806
arr_del15              0.258059
carrier_ct             0.139806
weather_ct             0.139806
nas_ct                 0.139806
security_ct            0.139806
late_aircraft_ct       0.139806
arr_cancelled          0.139806
arr_diverted           0.139806
arr_delay              0.139806
carrier_delay          0.139806
weather_delay          0.139806
nas_delay              0.139806
security_delay         0.139806
late_aircraft_delay    0.139806
dtype: float64

In [10]:
df[df.isnull().any(axis=1)].head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
3880,2023,6,MQ,Envoy Air,CLL,"College Station/Bryan, TX: Easterwood Field",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3894,2023,6,MQ,Envoy Air,EUG,"Eugene, OR: Mahlon Sweet Field",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,2023,6,MQ,Envoy Air,FSD,"Sioux Falls, SD: Joe Foss Field",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3904,2023,6,MQ,Envoy Air,GRB,"Green Bay, WI: Green Bay Austin Straubel Inter...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3910,2023,6,MQ,Envoy Air,HPN,"White Plains, NY: Westchester County",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df[(df['arr_flights'] > 0) & (df['arr_delay'].isna())]

Empty DataFrame
Columns: [year, month, carrier, carrier_name, airport, airport_name, arr_flights, arr_del15, carrier_ct, weather_ct, nas_ct, security_ct, late_aircraft_ct, arr_cancelled, arr_diverted, arr_delay, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 21 columns]

In [13]:
df[(df['carrier_ct'] > 0) & (df['carrier_delay'].isna())]

Empty DataFrame
Columns: [year, month, carrier, carrier_name, airport, airport_name, arr_flights, arr_del15, carrier_ct, weather_ct, nas_ct, security_ct, late_aircraft_ct, arr_cancelled, arr_diverted, arr_delay, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 21 columns]

In [14]:
df[(df['arr_flights'] == 0) & (df['arr_delay'].isna())]

Empty DataFrame
Columns: [year, month, carrier, carrier_name, airport, airport_name, arr_flights, arr_del15, carrier_ct, weather_ct, nas_ct, security_ct, late_aircraft_ct, arr_cancelled, arr_diverted, arr_delay, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 21 columns]

In [15]:
delay_cols = ['arr_delay','carrier_delay','weather_delay',
              'nas_delay','security_delay','late_aircraft_delay']

df[(df['arr_flights']==0) & (df[delay_cols].isna().any(axis=1))]

Empty DataFrame
Columns: [year, month, carrier, carrier_name, airport, airport_name, arr_flights, arr_del15, carrier_ct, weather_ct, nas_ct, security_ct, late_aircraft_ct, arr_cancelled, arr_diverted, arr_delay, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 21 columns]

In [16]:
df['sum_parts'] = (
    df['carrier_delay'] +
    df['weather_delay'] +
    df['nas_delay'] +
    df['security_delay'] +
    df['late_aircraft_delay']
)

df[df['arr_delay'].isna()][['arr_delay','sum_parts']].head()

      arr_delay  sum_parts
3880        NaN        NaN
3894        NaN        NaN
3898        NaN        NaN
3904        NaN        NaN
3910        NaN        NaN

In [17]:
df.loc[[3880,3894,3898,3904,3910], ['arr_flights']]

      arr_flights
3880          NaN
3894          NaN
3898          NaN
3904          NaN
3910          NaN

In [18]:
# Drop rows with missing flight counts
df = df.dropna(subset=['arr_flights'])

In [20]:
print(df.isnull().sum())

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights              0
arr_del15              203
carrier_ct               0
weather_ct               0
nas_ct                   0
security_ct              0
late_aircraft_ct         0
arr_cancelled            0
arr_diverted             0
arr_delay                0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
sum_parts                0
dtype: int64

In [19]:
print(df.isnull().sum()[df.isnull().sum() > 0])

arr_del15    203
dtype: int64

In [21]:
# Impute arr_del15 using carrier-airport average rate
df['arr_del15_rate'] = df['arr_del15'] / df['arr_flights']
df['arr_del15_rate'] = df.groupby(['carrier','airport'])['arr_del15_rate']\
                         .transform(lambda x: x.fillna(x.mean()))
df['arr_del15'] = df['arr_del15_rate'] * df['arr_flights']
df.drop(columns=['arr_del15_rate'], inplace=True)

In [22]:
print(df.isnull().sum()[df.isnull().sum() > 0])

arr_del15    1
dtype: int64

Missing values were analyzed carefully. Rows with missing arr_flights were dropped because they represent incomplete operational data. But the arr_del15 column is  imputed logically  based on observed patterns to preserve the integrity of the analysis. Filling NaN with 0 was avoided unless it was logically valid, ensuring that no false data was introduced.


#handle duplicate